### ISSUE TITLE
Mod request: CircuitVisualizer

### ISSUE THREAD

**Issue by Dimava** [raiguard/PipeVisualizer#12]
> https://www.reddit.com/r/factorio/comments/122yu1t/is_there_any_kind_of_circuit_view_in_game_or_a/
> Circuit wires are nearly impossible to follow visually. The red/green wires so often blend in with everything around them. It doesn't help that combinators have red and green wires on their sprites even when no wires are attached to them. Is there any way to view circuit connections in a graphically simplified view? I'd expect it to be essentially a black and white view for the most part, with wires being drawn as bright red and green straight lines from component to component. Only things directly related to the circuitry would get color (like combinator settings).

> [Soul-Burn](https://www.reddit.com/user/Soul-Burn/)
> Basically [Pipe Visualizer](https://mods.factorio.com/mod/PipeVisualizer) but for circuits? I personally don't know of such mod.

> [Justinjah91](https://www.reddit.com/user/Justinjah91/) OP
> YES! That is exactly like what I'm looking for, but for circuits

AFAIUnderstand asode changing the points generation this does not differ much from this mod

**Comment by raiguard** [comment]
I actually do plan on making this! However, it probably won't happen for a while, because I already have three ongoing mod rewrites, my job, and university stuff to do.

It's not nearly as simple as "changing the points generation" - circuit networks are fundamentally different API-wise, so it will not share as much code as you might think.

Closing this issue because it's not related to this mod.
