### ISSUE TITLE
Overlay on mouseover

### ISSUE THREAD

**Issue by TierreAsh** [raiguard/PipeVisualizer#20]
In previous versions you had pipe visualization pop up only on mouse-over - can you  return that function?

**Comment by raiguard** [comment]
I think the `H` hotkey is superior in every way to the old hover mode. Take some time to play with it and I'm sure you'll start thinking the same.

**Comment by HopefullyICanChangeThatNameLaterOn** [comment]
Why not implement a combination of both? 
Hovering for some quick local (sanity) checks. Pressing H to keep the visualisation persistent, e.g. to follow longer pipes. 
I would also like to get the hover-functionality back, because it's more intuitive and doesn't require that additional key press (which I need to press a lot when building something complex new).

**Comment by VerySmallRoach** [comment]
99% of the time I'm using this mod to have a quick look at one or a few fluid systems, often when running around, and using H like this is kind of awkward. Don't remember last time I wanted visualization to stick on the screen other than to look at how pretty it is.
I have reverted to previous version, so it is not that big of an issue for me (although I hope nothing will break in it after expansion release), but if you're looking for feedback, then here's one more guy who doesn't like H mode at all.
If adding hover mode is too cumbersome with new mod architecture, perhaps you could consider to release old version as a separate mod? Pipe Visualizer Legacy or something.

**Comment by TierreAsh** [comment]
In big systems persistent H may be too much. Mouse over can show if this pipe is really connected where you expect it or not. H .... well to really see how beautiful the system you designed :) After you did it.

**Comment by Valoneu** [comment]
I need my mouseover back :/, also am i the only one who thinks its a donwgrade in visual

**Comment by Nagapito** [comment]
I too, am a little disappointed for the removal of that functionality and replaced by another one that is not organically useful. 
Previous system just worked, pass the mouse, quick pick, all fine, move on.
New system forces you to have to search for a key on keyboard, and for some people, this is actually enough to be a distraction... it breaks the flow.
Previous system should never been removed!

I do enjoy the new system, but has an evolution of previous display of all pipe network system, not as a replacement of the quick peek system that existed.

Please re-introduce the previous system or I will just go back to the older version.

**Comment by raiguard** [comment]
Just to make sure, you're aware of `H` to highlight individual systems, right? Several people seem to think that the only option now is the `Shift+H` overlay.

I will look into re-adding hover mode in a future version since so many people miss it.

**Comment by Zmiy69** [comment]
For me, constantly pressing "H" is quite inconvenient. I tried playing with it, but for designing, it's not convenient—you're constantly looking for the button. I switched to this mod (previous version) because it had such a cool feature. I tried to go back to 1.0, but it throws an error, some conflict with other mods.

**Comment by Zmiy69** [comment]
> Я думаю, що `H`гаряча клавіша в усіх відношеннях краща за старий режим наведення. Знайдіть час, щоб пограти з ним, і я впевнений, що ви почнете думати так само.
Unfortunately, there are no other alternatives to play with or without. Given the option to disable mouse hover and the "Н" button, everyone will choose what is more convenient for them.

**Comment by martin-t** [comment]
Different people have different "work"flows, for me having to press H is vastly inferior, especially when i want to see where a long pipe leads while zoomed out. And then having to press H on the same pipe(line) again.

Another reason to restore the old behavior is discoverability. I found this mod by installing Nullius Momenti, i found it useful and i will install it in my other playthroughs too. If i needed to press a button, i'd a) try it a few times then forget about it b) more likely not discover it in the first place.

**Comment by espenst** [comment]
I have to agree with some of the previous writers. I almost do not use the mod anymore. The mouse over was superior for me, and the previous graphics displayed better what I wanted to see.

I will have to use an older version in order to continue using this, but I would love if these changes were configurable.

**Comment by kmod** [comment]
I found the new "H to activate" mode to be unhelpful, and downgraded back to the version with hover functionality (which IMO is the killer feature).

It seems like it could support both? Hover functionality (perhaps toggled like now) as well as H.

Another option to avoid confusion is to add a message to the mod saying that this functionality has been removed but you can get it back by downgrading?

**Comment by Nagapito** [comment]
I think you dont understand what we actually wanted and how much we loved the old system....

What you changed is so that, we have an onhover system that automatically highlights the whole network of the item we are hovering... You just made it so we dont have to press H while over an item.

And this is not what we are asking... at least not what I was talking about but I think the remaining community shares same view!!

What we wanted was what we had before:
When I have a maze of pipes and I over one pipe, I want to see the that whole pipe path hightlight, so I can see where it goes, where I failed a connection, where I incorrectly joined it with another pipe. Exactly what the previous system did! That is, it highlighted the pipe and only that pipe network.

The new overlay system is cumbersome, noisy, really distracting! 
Best way I have to describe it is... (actually fits the current time), its a Christmas tree!!
 I dont want to have a christmas tree light up with light bulbs on the every machine my pipe connects. I dont want to hover a machine and it lights a christmas tree of all pipes connected to it and also machines connected to those pipes.
![image](https://github.com/raiguard/PipeVisualizer/assets/4959346/ff45b25e-f73b-42d9-87b6-05e5f2e40a1b)
Can you really see where the water pipe goes with all the noise that suddenly was added to the screen?

Sorry if I sound a little harsh but... you do such amazing things and here... I dont know if its stubbornness wanting to use the new system and refusing to use the old one or you are just really not understanding that not only what the community is asking you but also not realizing how bad from a UX perspective this new system is. 
Maybe its me that is asking (or even demanding) too much...

Cheers


Edit: Ok, After playing a little more with it and comparing with the old system (I fixed the bugs and run both side by side) I can understand some of the benefits of your new system while also  being distracted by the noise and... I come to the conclusion that a very simple change can be done.
Give us the option to enable highlight or not highlight the machines. 
One option to enable/disable machine highlight for normal H mode or shift+H mode ( I like to call it management mode :P and I do like to have them highlighted here since I am looking at the "big picture")
And an option to enable/disable machine highlight for hover mode since here I want to quickly peek a pipe path, not get distracted by extra highlights that cause noise.

This way, everyone is happy!

What you think of it? 
If you want, since you are a busy person, I can submit a pull request
